[versions]
# libraries
annotations = "24.1.0"
openia = "0.18.2"
apacheCommons = "3.14.0"
lombok = "1.18.32"
jtokkit = "1.0.0"

# plugins
kotlin = "1.9.24"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.4"
qodana = "0.1.13"
kover = "0.7.6"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
openia = { group = "com.theokanning.openai-gpt3-java", name = "service", version.ref = "openia" }
apacheCommons = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommons" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jtokkit = { group = "com.knuddels", name = "jtokkit", version.ref = "jtokkit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }

